settings:
  hold_ms: 80
  release_gap_ms: 20
mappings:
  KEY_ENTER: [Up, Left, A, B]
  ' ': [Up, Left, A]
  '!': [Up, Left, B]
  '"': [Up, Left, X]
  '#': [Up, Left, Y]
  $: [Up, Right, A]
  '%': [Up, Right, B]
  '&': [Up, Right, X]
  '''': [Up, Right, Y]
  (: [Down, Right, A]
  ): [Down, Right, B]
  '*': [Down, Right, X]
  +: [Down, Right, Y]
  ',': [Down, Left, A]
  '-': [Down, Left, B]
  .: [Down, Left, X]
  /: [Down, Left, Y]
  '0': [L, R, A]
  '1': [L, R, B]
  '2': [L, R, X]
  '3': [L, R, Y]
  '4': [L, R, Up]
  '5': [L, R, Down]
  '6': [L, R, Left]
  '7': [L, R, Right]
  '8': [L, R, A, B]
  '9': [L, R, A, X]
  ':': [L, R, A, Y]
  ;: [L, R, A, Up]
  <: [L, R, A, Down]
  '=': [L, R, A, Left]
  '>': [L, R, A, Right]
  '?': [L, R, B, X]
  '@': [L, R, B, Y]
  A: [A]
  B: [B]
  C: [X]
  D: [Y]
  E: [Up]
  F: [Down]
  G: [Left]
  H: [Right]
  I: [L, A]
  J: [L, B]
  K: [L, X]
  L: [L, Y]
  M: [L, Up]
  N: [L, Down]
  O: [L, Left]
  P: [L, Right]
  Q: [R, A]
  R: [R, B]
  S: [R, X]
  T: [R, Y]
  U: [R, Up]
  V: [R, Down]
  W: [R, Left]
  X: [R, Right]
  Y: [L, A, B]
  Z: [R, A, B]
  '[': [Up, Left, A, Select]
  \: [Up, Left, B, Select]
  ']': [Up, Left, X, Select]
  ^: [Up, Left, Y, Select]
  _: [Up, Right, A, Select]
  '`': [Up, Right, B, Select]
  a: [A, Select]
  b: [B, Select]
  c: [X, Select]
  d: [Y, Select]
  e: [Up, Select]
  f: [Down, Select]
  g: [Left, Select]
  h: [Right, Select]
  i: [L, A, Select]
  j: [L, B, Select]
  k: [L, X, Select]
  l: [L, Y, Select]
  m: [L, Up, Select]
  n: [L, Down, Select]
  o: [L, Left, Select]
  p: [L, Right, Select]
  q: [R, A, Select]
  r: [R, B, Select]
  s: [R, X, Select]
  t: [R, Y, Select]
  u: [R, Up, Select]
  v: [R, Down, Select]
  w: [R, Left, Select]
  x: [R, Right, Select]
  y: [L, A, B, Select]
  z: [R, A, B, Select]
  '{': [Up, Right, X, Select]
  '|': [Up, Right, Y, Select]
  '}': [Down, Right, A, Select]
  '~': [Down, Right, B, Select]
  KEY_DELETE: [Down, Right, X, Select]
