#!/usr/bin/env python3
"""
gen_keymap.py — Generate SNES joypad→tile lookup table from config/mappings.yaml.

Outputs:
  ../assets/keymap.inc  — assembly table: .word bitmask, .word tile_number
                          one entry per printable ASCII char + special actions,
                          sentinel $0000,$0000

Special tile values (not real tiles, handled by ROM):
  $FFFF — delete/backspace: move cursor back and erase last character

Button bitmask layout (SNES $4218/$4219 as 16-bit word, high byte = $4218):
  bit 15  B       bit 14  Y       bit 13  Select  bit 12  Start
  bit 11  Up      bit 10  Down    bit  9  Left    bit  8  Right
  bit  7  A       bit  6  X       bit  5  L       bit  4  R

Tile number for ASCII char c (must match gen_font.py):
  C = ord(c) - 0x20
  tile = (C // 8) * 32 + (C % 8) * 2

Usage (from snes/ directory):
    make font
"""

import sys
from pathlib import Path

BUTTON_BITS = {
    'B':      0x8000,
    'Y':      0x4000,
    'Select': 0x2000,
    'Start':  0x1000,
    'Up':     0x0800,
    'Down':   0x0400,
    'Left':   0x0200,
    'Right':  0x0100,
    'A':      0x0080,
    'X':      0x0040,
    'L':      0x0020,
    'R':      0x0010,
}


def combo_to_bitmask(buttons: list[str]) -> int:
    mask = 0
    for btn in buttons:
        if btn not in BUTTON_BITS:
            raise ValueError(f"Unknown button: {btn!r}")
        mask |= BUTTON_BITS[btn]
    return mask


def char_to_tile(c: str) -> int:
    C = ord(c) - 0x20
    return (C // 8) * 32 + (C % 8) * 2


def main() -> None:
    try:
        import yaml
    except ImportError:
        sys.exit("Error: PyYAML not installed. Run: pip install pyyaml")

    mappings_path = Path(__file__).parent.parent.parent / "config" / "mappings.yaml"
    if not mappings_path.exists():
        sys.exit(f"mappings.yaml not found at {mappings_path}")

    with open(mappings_path, encoding="utf-8") as f:
        data = yaml.safe_load(f)

    mappings = data.get("mappings", {})

    out_dir = Path(__file__).parent.parent / "assets"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "keymap.inc"

    # Special keys: name → tile sentinel value
    SPECIAL_ACTIONS = {
        'KEY_DELETE': 0xFFFF,  # backspace: erase last char, move cursor back
    }

    entries = []
    skipped = []

    for key, buttons in mappings.items():
        key_str = str(key)
        if key_str in SPECIAL_ACTIONS:
            bitmask = combo_to_bitmask(buttons)
            tile    = SPECIAL_ACTIONS[key_str]
            entries.append((bitmask, tile, key_str, buttons))
            continue
        # Only handle single printable ASCII characters (0x20–0x7E)
        if len(key_str) != 1 or not (0x20 <= ord(key_str) <= 0x7E):
            skipped.append(key_str)
            continue
        bitmask = combo_to_bitmask(buttons)
        tile    = char_to_tile(key_str)
        entries.append((bitmask, tile, key_str, buttons))

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("; Auto-generated by tools/gen_keymap.py — do not edit manually.\n")
        f.write("; Format per entry: .word bitmask, .word tile_number\n")
        f.write("; Special tile $FFFF = delete/backspace action\n")
        f.write("; Sentinel: .word $0000, $0000\n\n")
        for bitmask, tile, char, buttons in entries:
            btn_str = "+".join(buttons)
            display = repr(char) if char in (" ", "'") else char
            f.write(f"    .word ${bitmask:04X}, ${tile:04X}  ; {display!s:<12} {btn_str}\n")
        f.write("    .word $0000, $0000  ; sentinel\n")

    special_count = sum(1 for _, t, _, _ in entries if t == 0xFFFF)
    char_count    = len(entries) - special_count
    print(f"keymap.inc: {char_count} chars + {special_count} special, {len(skipped)} skipped ({', '.join(skipped)})")


if __name__ == "__main__":
    main()
