#!/usr/bin/env python3
"""
gen_welcome.py -- Parse config/welcome.ini and generate ASM tile data.

Output:
  ../assets/welcome.inc -- .word entries for the SNES terminal welcome screen

Data format (consumed by print_welcome_msg in main.asm):
  $3Cxx / $3Dxx  -- tilemap word for a printable character
  $FFFF          -- newline (advance cursor_y, reset cursor_x)
  $0000          -- end sentinel

Limits (enforced with sys.exit):
  Max 26 lines   (VISIBLE_ROWS in main.asm)
  Max 30 chars/line  (USABLE_COLS in main.asm)
  ASCII 0x20..0x7E only

Usage (from snes/ directory):
    make
"""

import sys
from pathlib import Path

MAX_LINES = 26
MAX_COLS  = 30


def char_to_tile_word(ch: str) -> int:
    c = ord(ch) - 0x20
    n = (c // 8) * 32 + (c % 8) * 2
    return 0x3C00 | n


def main() -> None:
    ini_path = Path(__file__).parent.parent.parent / "config" / "welcome.ini"
    if not ini_path.exists():
        sys.exit(f"Error: welcome.ini not found at {ini_path}")

    raw_lines = ini_path.read_text(encoding="utf-8").splitlines()

    # Strip comments; preserve blank lines (they become blank screen rows)
    content_lines = [
        line.rstrip()
        for line in raw_lines
        if not line.lstrip().startswith((";", "#"))
    ]

    # Remove leading/trailing blank lines from the message
    while content_lines and content_lines[0] == "":
        content_lines.pop(0)
    while content_lines and content_lines[-1] == "":
        content_lines.pop()

    if len(content_lines) > MAX_LINES:
        sys.exit(
            f"Error: welcome.ini has {len(content_lines)} lines "
            f"(max {MAX_LINES}, VISIBLE_ROWS in main.asm)"
        )

    for i, line in enumerate(content_lines, 1):
        if len(line) > MAX_COLS:
            sys.exit(
                f"Error: line {i} has {len(line)} characters "
                f"(max {MAX_COLS}, USABLE_COLS in main.asm):\n  {line!r}"
            )
        for j, ch in enumerate(line, 1):
            if not (0x20 <= ord(ch) <= 0x7E):
                sys.exit(
                    f"Error: line {i}, col {j}: character {ch!r} "
                    f"(U+{ord(ch):04X}) is not ASCII printable (0x20..0x7E)"
                )

    out_dir  = Path(__file__).parent.parent / "assets"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "welcome.inc"

    total_chars = sum(len(line) for line in content_lines)

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("; Auto-generated by tools/gen_welcome.py -- do not edit manually.\n")
        f.write(f"; Source: config/welcome.ini -- {len(content_lines)} lines, {total_chars} chars\n")

        for line in content_lines:
            if line:
                for ch in line:
                    word = char_to_tile_word(ch)
                    f.write(f"    .word ${word:04X}  ; {ch!r}\n")
            f.write("    .word $FFFF  ; newline\n")

        f.write("    .word $0000  ; sentinel\n")

    print(f"welcome.inc     : {len(content_lines)} lines, {total_chars} chars")


if __name__ == "__main__":
    main()
