#!/usr/bin/env python3
"""
gen_keymap.py — Generate SNES joypad→tile lookup table from config/mappings.yaml.

Output:
  ../assets/keymap.inc — for the Mode 5 build (src/main.asm, BG2 2bpp,
                         16x16 dense-packed tiles).
                         tile = (C // 8) * 32 + (C % 8) * 2
                         (top-left 8×8 VRAM slot of the super-tile;
                         PPU auto-reads the +1, +16, +17 partners).

Each entry is `.word bitmask, .word tile_number`, one row per printable ASCII
character plus the special actions, terminated by the sentinel
`.word $0000, $0000`.

Special tile values (not real tiles, handled by ROM):
  $FFFF — delete/backspace: move cursor back and erase last character
  $FFFE — newline/enter: advance to next row, scroll if needed

Button bitmask layout (SNES $4218/$4219 as 16-bit word, high byte = $4218):
  bit 15  B       bit 14  Y       bit 13  Select  bit 12  Start
  bit 11  Up      bit 10  Down    bit  9  Left    bit  8  Right
  bit  7  A       bit  6  X       bit  5  L       bit  4  R

Usage (from snes/ directory):
    make font
"""

import sys
from pathlib import Path

BUTTON_BITS = {
    'B':      0x8000,
    'Y':      0x4000,
    'Select': 0x2000,
    'Start':  0x1000,
    'Up':     0x0800,
    'Down':   0x0400,
    'Left':   0x0200,
    'Right':  0x0100,
    'A':      0x0080,
    'X':      0x0040,
    'L':      0x0020,
    'R':      0x0010,
}


def combo_to_bitmask(buttons: list[str]) -> int:
    mask = 0
    for btn in buttons:
        if btn not in BUTTON_BITS:
            raise ValueError(f"Unknown button: {btn!r}")
        mask |= BUTTON_BITS[btn]
    return mask


def char_to_tile(c: str) -> int:
    """Mode 5 (BG2 2bpp, 16×16 dense-pack): top-left 8×8 VRAM slot.

    Matches `super_tile_vram_base` in gen_font.py: 8 super-tiles per
    row-pair with step 2 inside a row-pair (top row) and step 32 between
    row-pairs. The PPU auto-reads N, N+1, N+16, N+17 per tilemap entry
    so a single tilemap word per 16×16 cell is enough.
    """
    C = ord(c) - 0x20
    return (C // 8) * 32 + (C % 8) * 2


# Special keys: name → tile sentinel value.
SPECIAL_ACTIONS = {
    'KEY_DELETE': 0xFFFF,  # backspace: erase last char, move cursor back
    'KEY_ENTER':  0xFFFE,  # newline: advance to next row, scroll if needed
}


def build_entries(mappings):
    """Return (entries, skipped) for the Mode 5 tile-encoding function."""
    entries = []
    skipped = []
    for key, buttons in mappings.items():
        key_str = str(key)
        if key_str in SPECIAL_ACTIONS:
            bitmask = combo_to_bitmask(buttons)
            tile    = SPECIAL_ACTIONS[key_str]
            entries.append((bitmask, tile, key_str, buttons))
            continue
        if len(key_str) != 1 or not (0x20 <= ord(key_str) <= 0x7E):
            skipped.append(key_str)
            continue
        bitmask = combo_to_bitmask(buttons)
        # priority=1 (bit 13) + palette=7 (bits 12-10) = $3C00
        tile    = char_to_tile(key_str) | 0x3C00
        entries.append((bitmask, tile, key_str, buttons))
    return entries, skipped


def write_keymap(out_path: Path, entries) -> None:
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("; Auto-generated by tools/gen_keymap.py — do not edit manually.\n")
        f.write("; Target: src/main.asm (Mode 5, BG2 2bpp, 16x16 dense-pack).\n")
        f.write("; Tile field for ASCII char c: C = ord(c) - 0x20;\n")
        f.write(";     tile = (C // 8) * 32 + (C % 8) * 2\n")
        f.write("; The PPU auto-reads N, N+1, N+16, N+17 per tilemap entry, so the\n")
        f.write("; ROM writes a single 16-bit tilemap word per on-screen character.\n")
        f.write("; Format per entry: .word bitmask, .word tile_number\n")
        f.write("; Special tile $FFFF = delete/backspace, $FFFE = newline/enter\n")
        f.write("; Sentinel: .word $0000, $0000\n\n")
        for bitmask, tile, char, buttons in entries:
            btn_str = "+".join(buttons)
            display = repr(char) if char in (" ", "'") else char
            f.write(f"    .word ${bitmask:04X}, ${tile:04X}"
                    f"  ; {display!s:<12} {btn_str}\n")
        f.write("    .word $0000, $0000  ; sentinel\n")


def main() -> None:
    try:
        import yaml
    except ImportError:
        sys.exit("Error: PyYAML not installed. Run: pip install pyyaml")

    mappings_path = Path(__file__).parent.parent.parent / "config" / "mappings.yaml"
    if not mappings_path.exists():
        sys.exit(f"mappings.yaml not found at {mappings_path}")

    with open(mappings_path, encoding="utf-8") as f:
        data = yaml.safe_load(f)

    mappings = data.get("mappings", {})

    out_dir = Path(__file__).parent.parent / "assets"
    out_dir.mkdir(parents=True, exist_ok=True)

    entries, skipped = build_entries(mappings)
    write_keymap(out_dir / "keymap.inc", entries)

    special_count = sum(1 for _, t, _, _ in entries if t >= 0xFFFE)
    char_count    = len(entries) - special_count
    skipped_str   = ", ".join(skipped) if skipped else "none"
    print(f"keymap.inc      : {char_count} chars + {special_count} special "
          f"(tile = (C//8)*32 + (C%8)*2)")
    print(f"skipped entries : {skipped_str}")


if __name__ == "__main__":
    main()
